### ISSUE TITLE
Missing images in production

### ISSUE THREAD

**Issue by nhashmi** [ga-dc/wdidc5-project2#16]
# Our app's images are missing when we push to Heroku

I've tried implementing the solutions in [this Stack Overflow post](http://stackoverflow.com/questions/18324063/rails-4-images-not-loading-on-heroku) and in the guidelines on Heroku [here](https://devcenter.heroku.com/articles/rails-asset-pipeline) and [here](https://devcenter.heroku.com/articles/rails-4-asset-pipeline), but I haven't been able to get them to load. 

I'm not sure if I need to be doing some sort of precompiling before I push to Heroku, and I've tried putting the images in the public folder, but nothing seems to work.

**Comment by jshawl** [comment]
is the missing image in your css or in your html?

**Comment by jshawl** [comment]
can you paste the code you're using to generate the image

**Comment by luminousbeam** [comment]
someone said yesterday that you have to use image url's if you want them to show up on heroku, something about heroku and image api's...i think it was andy!

**Comment by nhashmi** [comment]
It's happening anywhere I've specified a background image in my CSS: 

``` scss
body {
  background-color: #f8f8f8;
  color: $dark-gray;
  line-height: 1.25em;
  font-size: 1.5em;
  margin: 0;
  background-image: url('map.jpg');
}
```

**Comment by nhashmi** [comment]
Images specified inline in my HTML do show up, for example a logo that is a link.

**Comment by jrhorn424** [comment]
Can you try this instead?

``` scss
body {
  background-color: #f8f8f8;
  color: $dark-gray;
  line-height: 1.25em;
  font-size: 1.5em;
  margin: 0;
  background-image: url(asset_url('map.jpg'));
}
```

If that doesn't work, try `asset_path` or `image_url`.
